name: disk-utilization-testing

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/disk-utilization-testing
  cancel-in-progress: true

jobs:
  default-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: see what is there - begin
        run: |
          df -h
          date
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          swap-storage: false
      - name: see what is there - end
        run: |
          date
          df -h
