name: faux-crucible-ci

on:
  pull_request:
    branches: [ master ]
    paths:
    - LICENSE
    - '**.md'
    - .github/workflows/faux-crucible-ci.yaml
    - 'docs/**'
  merge_group:
    paths:
    - LICENSE
    - '**.md'
    - .github/workflows/faux-crucible-ci.yaml
    - 'docs/**'

jobs:
  call-core-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/faux-core-crucible-ci.yaml@main
